# Generated by Django 3.2.4 on 2021-06-12 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_audio', models.FileField(upload_to='input-audio')),
                ('clean_audio', models.FileField(upload_to='clean-audio')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demoapp.user')),
            ],
        ),
    ]
